server:
  port: 8094
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
      - id: flightAppUser
        uri: http://localhost:8091/
        predicates:
        - Path=/api1/**          
      - id: flightAppAdmin
        uri: http://localhost:8092/
        predicates:
        - Path=/api2/**
      - id: flightAppAirline
        uri: http://localhost:8093/
        predicates:
        - Path=/api3/**  
  application:
    name: GATEWAY-API
        